# Generated by Django 5.2.7 on 2025-10-04 14:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_supplier', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999)], verbose_name='Código do Fornecedor')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_product', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999)], verbose_name='Codigo do Produto')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Produto')),
                ('category', models.CharField(choices=[('PERECIVEIS', 'Perecíveis'), ('NAOPERECIVEIS', 'Não Perecíveis')], max_length=50, verbose_name='Categoria')),
                ('barcode', models.CharField(max_length=13, unique=True, verbose_name='Código de Barras')),
                ('unit', models.CharField(choices=[('KG', 'Quilograma'), ('LT', 'Litro'), ('UN', 'Unidade')], max_length=2, verbose_name='Unidade')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade em Estoque')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmssistem.supplier', verbose_name='Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(max_length=50, unique=True, verbose_name='Código do Lote')),
                ('mfg_date', models.DateField(verbose_name='Data de Fabricação')),
                ('exp_date', models.DateField(verbose_name='Data de Validade')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade no Lote')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmssistem.product', verbose_name='Produto')),
            ],
            options={
                'unique_together': {('product', 'lot_code')},
            },
        ),
    ]
